language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      services:
        - docker
      before_script:
        - third_party/git_clone_googletest.sh
      script:
        - >-
          docker run -v ${TRAVIS_BUILD_DIR}:/build -w /build arbmind/qbs-clang10:qbs_v1.16.0
          build
          -d /tmp/build
          -p autotest-runner
    # - os: windows
    #   install:
    #     - choco install qbs
    #     - qbs setup-toolchains --detect
    #   before_script:
    #     - third_party/git_clone_googletest.sh
    #   script:
    #     - >-
    #       qbs build profile:MSVC2019-x64
    #       --file co-cpp19.qbs --build-directory ${TMP}/build
    #       -p autotest-runner
