name: Qbs-Tests

on: push

jobs:
  linux:
    name: "Linux"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - image: arbmind/qbs-clang:1.21.0-13
            build_args: "modules.cpp.cxxStandardLibrary:libc++ modules.cpp.staticLibraries:c++,c++abi"
          - image: arbmind/qbs-clang:1.21.0-14
            build_args: "modules.cpp.cxxStandardLibrary:libc++ modules.cpp.staticLibraries:c++,c++abi"
          - image: arbmind/qbs-clang-libstdcpp:1.21.0-14-11
          - image: arbmind/qbs-gcc:1.21.0-11

    steps:
      - uses: actions/checkout@v2

      - name: Get Googletest
        run: third_party/git_clone_googletest.sh

      - name: Build and run Tests
        run: >-
          docker run --rm -v ${GITHUB_WORKSPACE}:/project -w /project
          ${{ matrix.image }}
          build
          --build-directory /tmp/build
          ${{ matrix.build_args }}
          -p autotest-runner

  windows:
    name: "Windows"
    runs-on: windows-2019

    strategy:
      fail-fast: false
      matrix:
        include:
          - profile: MSVC2019-x64

    steps:
      - name: Install Qbs
        run: choco install qbs
      - name: Setup Qbs
        run: |
          qbs setup-toolchains --detect
          qbs config --list profiles

      - uses: actions/checkout@v2

      - name: Get Googletest
        run: third_party/git_clone_googletest.sh
        shell: bash

      - name: Build and run Tests
        run: >-
          qbs build profile:${{ matrix.profile }}
          --build-directory ${env:RUNNER_TEMP}\build
          -p autotest-runner
