name: Static Analyzer

on: push

jobs:
  clang-analyze:
    name: "Clang Static Analyzer"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - image: arbmind/cmake-clang:3.22.3-14
            preset: clang-analyze

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Analyze
        run: >-
          docker run --rm -v ${GITHUB_WORKSPACE}:/project -w /project
          ${{ matrix.image }}
          script/build_cmake.sh ${{ matrix.preset }} debug
